language: python
sudo: false
python:
- 2.7
- 3.4
- 3.5
- 3.6
cache: pip
install:
- pip install -e .[test]
script:
- py.test --cov=snapshottest tests examples/pytest
# Run Pytest Example
- py.test examples/pytest
after_success:
- coveralls
matrix:
  fast_finish: true
  include:
  - python: '2.7'
    install: pip install flake8
    script: flake8
